# 1. إعداد الوسائط العالمي (حسب التوثيق يستخدم input)
media:
  input: assets
  output: assets

# 2. تعريف المحتوى
content:
  - name: destinations
    label: "المقالات"
    type: collection
    path: data/destinations
    filename: "{primary}.json"
    view:
      fields: [title,image,published_at]
      primary: title
      sort: [published_at, title]
      default:
        sort: published_at
        order: desc
    fields:
      - name: title
        required: true
        label: "العنوان"
        type: string
      - name: image
        label: "الصورة الرئيسية"
        type: image
        required: true
        options:
          path: assets/articles_img
          unique: true
          rename: safe
      - name: published_at
        label: "تاريخ النشر"
        type: date
        hidden: true
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss
      - name: article
        label: "المحتوى"
        required: true
        type: rich-text
        options:
          format: html
          switcher: false
          path: assets/content_img
          rename: safe
          multiple:
            max: 35
          unique: true
  - name: Index
    label: index.json
    type: file
    path: data/destinations_index.json
    
