media:
  - name: All_Media
    input: assets
    output: assets
    hidden: true
  - name: images
    label: "معرض الصور"
    input: assets/gallery_img
    output: /assets/gallery_img
    rename: safe
    categories: [image]
  - name: docs
    label: Documents
    input: assets/content_img
    output: /assets/content_img
    categories: [image]
      
content:
  - name: destinations
    label: "المقالات"
    type: collection
    path: data/destinations
    filename: "{primary}.json"
    view:
      fields: [title,image,published_at]
      primary: title
      sort: [published_at]
      default:
        sort: published_at
        order: desc
    fields:
      - name: title
        required: true
        label: "العنوان"
        type: string
      - name: image
        label: "الصورة الرئيسية"
        type: image
        required: true
        options:
          path: assets/articles_img
          unique: true
          rename: safe
      - name: published_at
        label: "تاريخ النشر"
        type: date
        hidden: true
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss
      - name: article
        label: "المحتوى"
        required: true
        type: rich-text
        options:
          format: html
          switcher: false
          path: assets/content_img
          rename: safe
          multiple:
            max: 35
          unique: true
  - name: Upcoming
    label: "الرحلات القادمة"
    type: collection
    path: data/upcomingTrips
    filename: "{primary}.json"
    view:
      fields: [title,image,pricePerDay,date]
      primary: title
      sort: [date]
      default:
        sort: date
        order: desc
    fields:
      - name: title
        required: true
        label: "العنوان"
        type: string
      - name: date
        required: true
        label: "تاريخ الرحلة"
        type: date
        default: " "
        options:
          format: yyyy-MM-dd
      - name: duration
        required: true
        label: "عدد أيام الرحلة"
        type: number
        options:
          min: 1
          max: 69
      - name: image
        label: "الصورة الرئيسية"
        type: image
        required: true
        options:
          path: assets/upcomingTrips_img
          rename: safe
      - name: route
        required: true
        label: "مسار الرحلة"
        type: string
        list: true
      - name: pricePerDay
        required: true
        label: "السعر لليوم الواحد"
        type: number
        options:
          min: 1
      - name: inclusions
        required: true
        label: "السعر شامل"
        type: string
        list: true
      - name: itinerary
        required: true
        label: "السعر غير شامل"
        type: string
        list: true
      - name: description
        label: "نبذة عن الرحلة"
        required: true
        type: rich-text
        options:
          format: html
          switcher: false
          path: assets/content_img
          rename: safe
          multiple:
            max: 35
          unique: true
