backend:
  name: github
  repo: sandexpert/sand-expert
  branch: main

media_folder: "assets/articles_img"
public_folder: "/assets/articles_img"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Content", name: "body", widget: "markdown" }
